[global]
# Konfiguracja globalna aplikacji
developmentMode = false

[server]
# Ustawienia serwera
headless = true
port = 8501
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = false

[browser]
# Ustawienia przeglądarki
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Motyw aplikacji
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[client]
# Ustawienia klienta
showErrorDetails = true

[runner]
# Ustawienia runnera
magicEnabled = true
